station-event-cockroach-migration-announcement = Atenção. Um grande influxo de formas de vida desconhecidas foi detectado nos sistemas de ventilação da estação. Por favor, livrem-se dessas criaturas antes que elas comecem a afetar a produtividade.
station-event-slimes-spawn-announcement = Atenção. Um grande influxo de formas de vida desconhecidas foi detectado nos sistemas de ventilação da estação. Por favor, livrem-se dessas criaturas antes que elas comecem a afetar a produtividade.
station-event-vent-critters-announcement = Atenção. Um grande influxo de formas de vida desconhecidas foi detectado nos sistemas de ventilação da estação. Por favor, livrem-se dessas criaturas antes que elas comecem a afetar a produtividade.
station-event-spider-spawn-announcement = Atenção. Um grande influxo de formas de vida desconhecidas foi detectado nos sistemas de ventilação da estação. Por favor, livrem-se dessas criaturas antes que elas comecem a afetar a produtividade.
station-event-reagentslime-vents-announcement = Atenção. Um grande influxo de formas de vida desconhecidas foi detectado nos sistemas de ventilação da estação. Por favor, livrem-se dessas criaturas antes que elas comecem a afetar a produtividade.
station-event-meat-vents-announcement = Atenção. Um grande influxo de formas de vida desconhecidas foi detectado nos sistemas de ventilação da estação. Por favor, livrem-se dessas criaturas antes que elas comecem a afetar a produtividade.
station-event-neutral-xeno-vents-announcement = Avistamentos de vida selvagem alienígena confirmados na estação. É aconselhado que os tripulantes se armem, barrem as portas e se defendam, se necessário. A segurança é aconselhada a investigar a ameaça o mais rápido possível.
station-event-tick-vents-announcement = Avistamentos de vida selvagem alienígena confirmados na estação. É aconselhado que os tripulantes se armem, barrem as portas e se defendam, se necessário. A segurança é aconselhada a investigar a ameaça o mais rápido possível.
station-event-argocyte-vents-announcement = Avistamentos de vida selvagem alienígena confirmados na estação. É aconselhado que os tripulantes se armem, barrem as portas e se defendam, se necessário. A segurança é aconselhada a investigar a ameaça o mais rápido possível.
station-event-light-vents-announcement = Avistamentos de vida selvagem alienígena confirmados na estação. É aconselhado que os tripulantes se armem, barrem as portas e se defendam, se necessário. A segurança é aconselhada a investigar a ameaça o mais rápido possível.
station-event-carp-vents-announcement = Avistamentos de vida selvagem alienígena confirmados na estação. É aconselhado que os tripulantes se armem, barrem as portas e se defendam, se necessário. A segurança é aconselhada a investigar a ameaça o mais rápido possível.
station-event-space-vents-announcement = Avistamentos de vida selvagem alienígena confirmados na estação. É aconselhado que os tripulantes se armem, barrem as portas e se defendam, se necessário. A segurança é aconselhada a investigar a ameaça o mais rápido possível.
# Weak
station-event-slimes-spawn-weak-announcement = Atenção. Um influxo moderado de formas de vida desconhecidas foi detectado nos sistemas de ventilação da estação. Por favor, livrem-se dessas criaturas antes que elas comecem a afetar a produtividade.
station-event-spider-spawn-weak-announcement = Atenção. Um influxo moderado de formas de vida desconhecidas foi detectado nos sistemas de ventilação da estação. Por favor, livrem-se dessas criaturas antes que elas comecem a afetar a produtividade.