- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Bagel
  - Barratry
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  - Train

  # Mapas do Pirata
  - Falcon
  - RadStation
  - Gaxstation
  - Glacier
  - Esperanza
  #- EstacaoPirata